#ifndef CONFIG_H
#define CONFIG_H

#define SETTING_SPLIT_COUNTER 1
#define SETTING_MINOR_COUNTER_WIDTH 56
#define SETTING_MINOR_COUNTER_COUNT 128
#define SETTING_ARTY_LOG2 7
#define SETTING_HEIGHT 4
#define SETTING_PROTECTION_BASE 0x90000000
#define SETTING_PROTECTION_SIZE 0x400000000
#define SETTING_PROTECTION_SIZE_GRAIN 64
#define SETTING_CACHE_WAYS_LOG2 2
// Number of 64B data blocks per MAC entry (default: 8 = 1KB coverage)
#define SETTING_MAC_COVERAGE_BLOCKS 8

#endif
