#ifndef CONFIG_H
#define CONFIG_H

#define SETTING_SPLIT_COUNTER 0
#define SETTING_MINOR_COUNTER_WIDTH 56
#define SETTING_MINOR_COUNTER_COUNT 8
#define SETTING_ARTY_LOG2 3
#define SETTING_HEIGHT 10
#define SETTING_PROTECTION_BASE 0x90000000
#define SETTING_PROTECTION_SIZE 0x400000000
#define SETTING_CACHE_WAYS_LOG2 2

#endif
