#ifndef CONFIG_H
#define CONFIG_H

#define SETTING_MINOR_COUNTER_WIDTH 3
#define SETTING_MINOR_COUNTER_COUNT 128
#define SETTING_ARTY_LOG2 7
#define SETTING_HEIGHT 4
#define SETTING_PROTECTION_BASE 0x90000000
#define SETTING_PROTECTION_SIZE 0x400000000
#define SETTING_CACHE_WAYS_LOG2 2

#endif
