#ifdef __cplusplus
extern "C" {
#endif

#pragma once

#include <stdint.h>
#include <stddef.h>
#include "reg_map.h"

// Async AES-XOR integrated block base:
// same rule as riscv/mmio_devices/aes_xor_async_addrmap.h
#define AES_XOR_ASYNC_BASE      (MEMREQ_BASE)
#define AES_XOR_ASYNC_CTRL_SIZE 0x00000100ULL

#define AES_XOR_ASYNC_NONCE_0   0x00ULL
#define AES_XOR_ASYNC_NONCE_1   0x08ULL
#define AES_XOR_ASYNC_NONCE_2   0x10ULL
#define AES_XOR_ASYNC_NONCE_3   0x18ULL
#define AES_XOR_ASYNC_NONCE_4   0x20ULL
#define AES_XOR_ASYNC_NONCE_5   0x28ULL
#define AES_XOR_ASYNC_NONCE_6   0x30ULL
#define AES_XOR_ASYNC_NONCE_7   0x38ULL
#define AES_XOR_ASYNC_CTRL      0x40ULL
#define AES_XOR_ASYNC_XOR_CFG   0x48ULL
#define AES_XOR_ASYNC_LAST_DONE 0x50ULL
#define AES_XOR_ASYNC_STATUS    0x58ULL
#define AES_XOR_ASYNC_INFLIGHT  0x60ULL
#define AES_XOR_ASYNC_REQ_ID    0x68ULL

#define AES_XOR_ASYNC_NONCE_0_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_0)
#define AES_XOR_ASYNC_NONCE_1_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_1)
#define AES_XOR_ASYNC_NONCE_2_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_2)
#define AES_XOR_ASYNC_NONCE_3_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_3)
#define AES_XOR_ASYNC_NONCE_4_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_4)
#define AES_XOR_ASYNC_NONCE_5_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_5)
#define AES_XOR_ASYNC_NONCE_6_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_6)
#define AES_XOR_ASYNC_NONCE_7_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_NONCE_7)
#define AES_XOR_ASYNC_CTRL_REG    REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_CTRL)
#define AES_XOR_ASYNC_XORCFG_REG  REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_XOR_CFG)
#define AES_XOR_ASYNC_LAST_DONE_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_LAST_DONE)
#define AES_XOR_ASYNC_STATUS_REG  REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_STATUS)
#define AES_XOR_ASYNC_INFLIGHT_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_INFLIGHT)
#define AES_XOR_ASYNC_REQ_ID_REG REG64(AES_XOR_ASYNC_BASE, AES_XOR_ASYNC_REQ_ID)

// CTRL bit fields
#define AES_XOR_CTRL_START_BIT          (1ULL << 0)
#define AES_XOR_CTRL_LAST_IN_GROUP_BIT  (1ULL << 1)
#define AES_XOR_CTRL_AES_ID_SHIFT       2ULL

// XOR_CFG bit fields
#define AES_XOR_CFG_IN_FROM_REQIO_BIT   (1ULL << 0)
#define AES_XOR_CFG_OUT_TO_REQIO_BIT    (1ULL << 1)
#define AES_XOR_CFG_SPM_OFFSET_SHIFT    2ULL
#define AES_XOR_CFG_SPM_OFFSET_MASK     0x1FFFFFFFULL
#define AES_XOR_CFG_DMA_ID_SHIFT        31ULL

#ifdef __cplusplus
}
#endif
